CREATE TABLE MEMBERS (
    MEMBER_ID     VARCHAR2(20) PRIMARY KEY,
    MEMBER_NAME   VARCHAR2(100),
    MEMBER_EMAIL  VARCHAR2(100),
    LOAN_LIMIT    NUMBER
);

CREATE TABLE BOOKS (
    BOOK_ID         VARCHAR2(20) PRIMARY KEY,
    ISBN            VARCHAR2(20),
    TITLE           VARCHAR2(100),
    AUTHOR          VARCHAR2(100),
    GENRE           VARCHAR2(50),
    YEAR            NUMBER,
    CLASS_ID        VARCHAR2(10),
    B_LOAN_LENGTH   VARCHAR2(20),
    BOOK_QUANTITY   NUMBER
);

CREATE TABLE EBOOKS (
    EBOOK_ID         VARCHAR2(20) PRIMARY KEY,
    ISBN             VARCHAR2(20),
    TITLE            VARCHAR2(100),
    AUTHOR           VARCHAR2(100),
    GENRE            VARCHAR2(50),
    YEAR             NUMBER,
    EB_LOAN_LENGTH   VARCHAR2(20),
    EBOOK_QUANTITY   NUMBER
);

CREATE TABLE EQUIPMENT (
    EQUIPMENT_ID     VARCHAR2(20) PRIMARY KEY,
    TYPE             VARCHAR2(50),
    MODEL            VARCHAR2(50),
    MAKE             VARCHAR2(50),
    E_LOAN_LENGTH    VARCHAR2(20),
    EQUIP_QUANTITY   NUMBER,
    LOAN_TYPE        VARCHAR2(50)
);

CREATE TABLE RESERVATIONS (
    RESERVATION_ID      VARCHAR2(20) PRIMARY KEY,
    RESOURCE_ID         VARCHAR2(20),
    MEMBER_ID           VARCHAR2(20),
    NOTIFICATIONS       NUMBER,
    DATE_LAST_NOTIFIED  DATE
);

CREATE TABLE RESOURCES (
    RESOURCE_ID     VARCHAR2(20) PRIMARY KEY,
    BOOK_ID         VARCHAR2(20),
    EBOOK_ID        VARCHAR2(20),
    EQUIPMENT_ID    VARCHAR2(20)
);

CREATE TABLE CLASS (
    CLASS_ID   VARCHAR2(10) PRIMARY KEY,
    FLOOR      NUMBER,
    SHELF      VARCHAR2(10)
);

CREATE TABLE LOANS (
    LOANS_ID       VARCHAR2(20) PRIMARY KEY,
    MEMBER_ID      VARCHAR2(20),
    RESOURCE_ID    VARCHAR2(20),
    LOAN_DATE      DATE,
    DATE_RETURNED  DATE
);

CREATE TABLE FINES (
    FINE_ID     VARCHAR2(20) PRIMARY KEY,
    MEMBER_ID   VARCHAR2(20),
    AMOUNT      NUMBER
);
