-- Link RESOURCES to BOOKS
ALTER TABLE RESOURCES
ADD CONSTRAINT fk_book_id
FOREIGN KEY (BOOK_ID)
REFERENCES BOOKS (BOOK_ID);

-- Link RESOURCES to EBOOKS
ALTER TABLE RESOURCES
ADD CONSTRAINT fk_ebook_id
FOREIGN KEY (EBOOK_ID)
REFERENCES EBOOKS (EBOOK_ID);

-- Link RESOURCES to EQUIPMENT
ALTER TABLE RESOURCES
ADD CONSTRAINT fk_equipment_id
FOREIGN KEY (EQUIPMENT_ID)
REFERENCES EQUIPMENT (EQUIPMENT_ID);

-- Link BOOKS to CLASS
ALTER TABLE BOOKS
ADD CONSTRAINT fk_class_id
FOREIGN KEY (CLASS_ID)
REFERENCES CLASS (CLASS_ID);

-- Link RESERVATIONS to MEMBERS
ALTER TABLE RESERVATIONS
ADD CONSTRAINT fk_member_id
FOREIGN KEY (MEMBER_ID)
REFERENCES MEMBERS (MEMBER_ID);

-- Link RESERVATIONS to RESOURCES
ALTER TABLE RESERVATIONS
ADD CONSTRAINT fk_resource_id
FOREIGN KEY (RESOURCE_ID)
REFERENCES RESOURCES (RESOURCE_ID);

-- Link LOANS to MEMBERS
ALTER TABLE LOANS
ADD CONSTRAINT fk_loan_member_id
FOREIGN KEY (MEMBER_ID)
REFERENCES MEMBERS (MEMBER_ID);

-- Link LOANS to RESOURCES
ALTER TABLE LOANS
ADD CONSTRAINT fk_loan_resource_id
FOREIGN KEY (RESOURCE_ID)
REFERENCES RESOURCES (RESOURCE_ID);

-- Link FINES to MEMBERS
ALTER TABLE FINES
ADD CONSTRAINT fk_fines_member_id
FOREIGN KEY (MEMBER_ID)
REFERENCES MEMBERS (MEMBER_ID);
